### PR TITLE
Adds Rick_Hanton.md

### PR DESCRIPTION
**Pull request by sinak**

### CODE REVIEW

**Comment by sinak** [comment]
Confirmation is here: https://twitter.com/rack88/status/809177579924111360

**Comment by sinak** [comment]
This needs to be updated; just got word that person has moved to Choice Hotels. Will send updated PR.

**Comment by sinak** [comment]
Updated.

**Comment by zestyping** [comment]
Hi, I'm sorry, we can't accept signature requests on behalf of other people.  Could you please have Rick Hanton send us a message himself if he wants to sign?  For example, he can tweet a link to this PR with his approval and that will be sufficient.  Thanks!

**Comment by lizthegrey** [comment]
I'll close this out and reply to tweet with a "here's a one-click button to sign"

**Pull request closed without merging**
