### PR TITLE
SignBot: Add signatory 'Will Salisbury' (willsalz)

### PR DESCRIPTION
**Pull request by lizthegrey**
Twitter user: https://twitter.com/willsalz
Created: 2010-12-05 19:12:16 +0000 UTC, Followers: 85, Following: 197, Tweets: 783, Egg: false

Twitter profile fields:
Name: Will Salisbury
Website: http://t.co/CxWLio16FD
Tagline: `WYSIWYG`

Personal page: willsalz.co

Signature file contents:
```
---
  name: "Will Salisbury"
  link: https://twitter.com/willsalz
  affiliation: "Uber"
  occupation_title: "Software Engineer"
---
```

### CODE REVIEW

**Comment by willsalz** [comment]
ping!

**Comment by zestyping** [comment]
Hi @willsalz, can you help us confirm that you work at Uber?  A LinkedIn page or an established personal website with a resume would work, or you could email us at neveragaindottech at gmail.com from an @uber email address.  Thank you!

**Comment by willsalz** [comment]
https://www.linkedin.com/in/williamsalisbury

**Comment by zestyping** [comment]
Thank you!  Added.

**Pull request merged**
