### PR TITLE
Add vijaykramesh to the list

### PR DESCRIPTION
**Pull request by vijaykramesh**
note this also fixes a missing newline right before my name appears.

### CODE REVIEW

**Comment by vijaykramesh** [comment]
merged upstream for you @emhoracek

**Comment by emhoracek** [comment]
@vijaykramesh Thanks for the help, but don't worry too much about it. Some volunteers will fix it up later.

**Comment by vijaykramesh** [comment]
cool. this is mergeable as is now though, since I already fixed it 👍

**Comment by vijaykramesh** [comment]
haha, axe that another merge added conflicts again.  

as a side note, I don't think git is the best way to track lines changing like this since it creates merge conflicts anytime two names are added near each other.

**Comment by emhoracek** [comment]
Trust us, we know that now. WE KNOW :sob:

**Comment by zestyping** [comment]
I've added you.  Thanks for signing!

**Pull request closed without merging**
