### PR TITLE
LPL, from board of directors

### PR DESCRIPTION
**Pull request by freddymartinez9**
Voted on today by board.

### CODE REVIEW

**Comment by sabo** [comment]
Hi, the way it's written, the pledge is really about individual action, so we'd prefer it if individuals signed with an organizational affiliation rather than en masse

**Comment by freddymartinez9** [comment]
Alright so I think this is a distinction without a difference. The point of doing pledges like this is to **build communities** and to acknowledge individual positions which we (collectively) find untenable. However, if we limit this to individuals, without organizational support, we are doomed to fail. These sorts of pledges are far more powerful if entire organizational teams sign on. However, the Hadoop or ..say the Security ... team at Uber taking a pledge like this is far more powerful given the [current situation we find ourselves in](https://www.engadget.com/2016/12/12/uber-workers-spied-on-celebrities/). I don't see a purpose in drawing a line for individuals but I am welcome to hear your thoughts. 

I have more thoughts but I will leave this short for now.

Regards.

**Comment by zestyping** [comment]
Freddy, would you and the other directors be okay signing as Director, Lucy Parsons Labs?  I think this would accomplish much the same goal.

**Comment by freddymartinez9** [comment]
@zestyping yes I am okay with that. We can close this one and we will open a new one with the new formatting.

**Pull request closed without merging**
