### PR TITLE
Jesús Leganés-Combarro "piranna"

### PR DESCRIPTION
**Pull request by piranna**

### CODE REVIEW

**Comment by piranna** [comment]
Why it has been closed without merge?

**Comment by mjg59** [comment]
We changed the format that signatures are being stored in and autogenerated a new merge that incorporated the conflicting PRs. Your signature should be present on the website now.

**Comment by piranna** [comment]
> We changed the format that signatures are being stored in and autogenerated a new merge that incorporated the conflicting PRs. Your signature should be present on the website now.

It's not on the website, but yes, [I've found that's being stored](https://github.com/neveragaindottech/neveragaindottech.github.io/blob/24bc0453a84e84d1b4e7baa934e1b3c99958c96b/_signatures/piranna.md), thank you.

**Comment by zestyping** [comment]
I checked just now, and it's there on the website.

**Pull request closed without merging**
