### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by therrij**

### CODE REVIEW

**Comment by emhoracek** [comment]
Hi, @therrij, could you fix your PR so you're only editing the line with your signature?

**Comment by dhartunian** [comment]
@therrij do you have any way to confirm your identity as the signer?

**Comment by zestyping** [comment]
Hi @therrij, we need a way to confirm that the GitHub account therrij actually belongs to Justin Therrien, Lexington Solutions — can you help us out with that info?

**Comment by natdempk** [comment]
Hi,

Since you originally submitted this pull request, the format used for the site has changed. Instead of modifying `index.html` directly, can you please create a markdown file with your information, following the directions here: https://github.com/neveragaindottech/neveragaindottech.github.io#to-add-your-name-via-github

Afterwards you can either modify this pull request and reopen it, or close it and create a new one.

Thanks!

**Pull request closed without merging**
