### PR TITLE
Create Qasim_Javed_Google.md

### PR DESCRIPTION
**Pull request by nixbox**
Add Qasim Javed's signature.

### CODE REVIEW

**Comment by zestyping** [comment]
Hi, can you help us confirm that the GitHub account nixbox is owned by Qasim Javed?  Thanks!

**Comment by nixbox** [comment]
Yes. It's owned by me. What else can I do?

**Comment by ichthyos** [comment]
Hi, thank you for your pull request.  To add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Could you please put a link to your GitHub account on an established webpage (such as your Keybase or LinkedIn profile, or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.

Thanks!

**Comment by lizthegrey** [comment]
There's sufficient info in gh account - look at https://github.com/nixbox/configs for instance which shows the name of the committer.

**Pull request merged**
