### PR TITLE
Add Automattic

### PR DESCRIPTION
**Pull request by melchoyce**
This is a continuation of #1073.

I am submitting this PR on behalf of:

Anne McCarthy
Ashleigh Axios
Aviva Pinchas
Caroline Moore
Cheri Lucas Rowlands
Chris Rudzki
Corey McKrill
Daryl L. L. Houston
Diana Potter
Doug Aitken
Elizabeth Urello
Enej Bajgorić
James Huff
James Tien
John Maeda
Justin Shreve
Kat Hagan
Kellie Peterson
Laurel Fulford
Liz Karkosk
Lori McLeese
Marjorie R. Asturias
Mark Armstrong
Mark Drovdahl
Matt Perry
Matt Sherman
Mel Choyce
Melanie Harari
Mindy Postoff
Nick Daugherty
Payton Swick
Philip John
Rodrigo Primo
Ryan Boren
Ryan Cowles
Ryan Markel
Steve Blythe
Stéphane Boisvert
Toni Schneider

Thanks again!

### CODE REVIEW

**Comment by ryanprior** [comment]
Hi, this is great news! Welcome, Automattic.

Can you provide verification of the identities, affiliation, and consent of the listed people? Having them e-mail or tweet would be fine. The list administrators are cautious about accepting signatures that aren't provided by the first-party.

Thank you!

**Comment by vaurora** [comment]
Hey all, this commit has been verified in terms of the identities (ask @vaurora on the Slack for confirmtion). It still needs review for formatting.

**Comment by hurtstotouchfire** [comment]
Yay! Hi @melchoyce!

**Comment by melchoyce** [comment]
Thanks everyone! 🎉

**Pull request merged**
