### PR TITLE
Create DanLupescu

### PR DESCRIPTION
**Pull request by mrshides**
I created the github account to sign the form, I am not a programmer and do not otherwise use github, I am a network engineer/security analyst.

### CODE REVIEW

**Comment by knuevena** [comment]
@mrshides Hi, thanks for submitting your pull request.  Unfortunately, it's not in the right format, so we can't accept it as is.

Please fix the indentation (the second line is out of sync with the others) and I'll merge this.

Thanks!

**Comment by mrshides** [comment]
done, thank you!

**Comment by zestyping** [comment]
@mrshides Hi there.  Sorry, but to accept this signature we need a way to verify that a person named "Dan Lupescu" owns this GitHub account.  Do you have a LinkedIn profile, Keybase page, established personal website, or Twitter account that has your name on it and shows (or where you can post) that this is your GitHub account?

**Comment by mrshides** [comment]
https://twitter.com/MrShides

**Comment by ichthyos** [comment]
Sorry that wasn't quite specific enough -- on Twitter could you post that your GitHub profile is https://github.com/mrshides ?

**Comment by mrshides** [comment]
done

**Comment by ichthyos** [comment]
Thank you!

**Pull request merged**
