### PR TITLE
Markup fixes

### PR DESCRIPTION
**Pull request by csippel**
### What

* fixed stray `</a>` tag
* added `</section>`, `</body>`, and `</html>`

### CODE REVIEW

**Comment by shaunagm** [comment]
Hi @csippel, can you put any changes beyond adding your signature into a separate pull request?  Thanks.

**Comment by hurtstotouchfire** [comment]
@shaunagm I think this *is* exclusively an enhancement PR.

@csippel can you consider re-doing this after https://github.com/neveragaindottech/neveragaindottech.github.io/pull/529 merges? It will obsolete this.

**Comment by csippel** [comment]
@hurtstotouchfire Yep, I'm going to go through the whole markup after the new feature is fully merged.

**Comment by hurtstotouchfire** [comment]
@csippel FYI that merged

**Pull request closed without merging**
