### PR TITLE
Create patrick_c_griffin.md

### PR DESCRIPTION
**Pull request by padraiceen**

### CODE REVIEW

**Comment by RichardEpsilonHughes** [comment]
Patrick, before I can merge this, the markdown file needs to be edited to match the format of the master template: https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.md

**Comment by padraiceen** [comment]
Corrected formatting

**Comment by lizthegrey** [comment]
Is there anything that verifies that someone named Patrick Griffin owns this github account? I see you created the github account just to sign the pledge.

If you have a twitter account, you may find it easier to use https://sign.neveragain.tech

**Comment by padraiceen** [comment]
That's me, I did create the account specifically for this purpose.  I'll use your alternative.  Thanks!

**Pull request closed without merging**
