### PR TITLE
Create Elizabeth_Peck_Verang_LLC.md

### PR DESCRIPTION
**Pull request by elizabethpeck**
I created my GitHub account just to sign this pledge so I do not have a link to submit here.

### CODE REVIEW

**Comment by zestyping** [comment]
For newly created GitHub accounts, we need something that links to this GitHub account from a page that you own.  Do you have a LinkedIn profile or public webpage that says you work for Verang LLC?

Alternatively, you can remove the affiliation and add a `link:` field pointing to a public webpage (blog, personal homepage, LinkedIn page) you own with your name on it, and we'll accept that.

**Comment by elizabethpeck** [comment]
I've updated my linked in profile just for you!


https://www.linkedin.com/in/elizabeth-peck-67871817?authType=NAME_SEARCH&authToken=zXdM&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A58511036%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1481923565158%2Ctas%3Aelizabeth

Elizabeth Peck | LinkedIn<https://www.linkedin.com/in/elizabeth-peck-67871817?authType=NAME_SEARCH&authToken=zXdM&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A58511036%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1481923565158%2Ctas%3Aelizabeth>
www.linkedin.com
View Elizabeth Peck's professional profile on LinkedIn. LinkedIn is the world's largest business network, helping professionals like Elizabeth Peck discover inside connections to recommended job candidates, industry experts, and business partners.





________________________________

**Comment by ichthyos** [comment]
Thanks for adding the Verang LLC verification to your LinkedIn -- could you also add the GitHub profile link so we're certain this is you? I believe there's a spot to do that in the Contact Info section.

**Comment by elizabethpeck** [comment]
Ok, I think I added https://github.com/elizabethpeck as a website to my LinkedIn profile?

[https://avatars2.githubusercontent.com/u/24609042?v=3&s=400]<https://github.com/elizabethpeck>

elizabethpeck<https://github.com/elizabethpeck>
github.com
elizabethpeck has 1 repository available. Follow their code on GitHub.


a


________________________________

**Comment by ichthyos** [comment]
Thank you!!

**Pull request merged**
