### PR TITLE
Add Seraphi Sigma

### PR DESCRIPTION
**Pull request by b3sigma**
Thanks!

### CODE REVIEW

**Comment by codersquid** [comment]
Hi, may we have information to verify that Seraphi Sigma is the identity linked to b3sigma?

**Comment by b3sigma** [comment]
Uh, aside from the fact that both have my legal last name, Sigma, in them? Not without annoying difficulty. If you are asking me to scan my id and send it to you or something, I might have to decline as I have strongly held and well justified reasons for limiting digitization of legal documentation.

**Comment by RichardEpsilonHughes** [comment]
Fair enough. Welcome to the host, Seraph.

**Comment by hypatia** [comment]
Hey @b3sigma, I'm one of the pledge authors and just wanted to apologize for how long this took - we're being meticulous around making sure that no faked signatures get onto the pledge, because this is often a problem with open letters, petitions, etc. We should have looked first at your github profile and seen that it's obviously a real account you use all the time and accepted it right away. Thanks for your patience with us.

**Comment by b3sigma** [comment]
No worries! I really appreciate that you started this important initiative so thank you! :smile:

**Comment by codersquid** [comment]
@b3sigma I'd also like to apologize. I am still learning how cautious to be when adding people. I took a look at your github account, and you have some nice repos! but I wasn't sure how strict to be. I will try to do better!

**Pull request merged**
