### PR TITLE
Create Jinghao_Liu_SQL_Server.md

### PR DESCRIPTION
**Pull request by jinghaol**
https://github.com/jinghaol/

### CODE REVIEW

**Comment by currymj** [comment]
Hi, thank you for your pull request.  To add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Could you please put a link to your GitHub account on an established webpage (such as your LinkedIn profile or personal site) that represents you by the name and affiliation in your signature? 

Please reply with the URL of that webpage, and we'll take a look.

Thanks!

**Comment by jinghaol** [comment]
https://www.linkedin.com/in/jinghao-liu-a169923

**Comment by ichthyos** [comment]
Hi,

I don't see the GitHub profile link on your LinkedIn profile -- could you add the link? I believe there is a place to add links in the Contact Info area of your LinkedIn profile.

Thanks!

**Comment by zestyping** [comment]
The GitHub account has a @microsoft.com address, so I'll accept it.

**Pull request merged**
