### PR TITLE
Create Paul_Callahan_Syapse.md

### PR DESCRIPTION
**Pull request by paulcsyapse**

### CODE REVIEW

**Comment by neverett** [comment]
Hey Paul, to add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Can you put a link to your GitHub account on an established webpage (such as your Keybase or LinkedIn profile, or personal site) that represents you by the name and affiliation in your signature? Please comment here with the URL of that webpage, and we'll take a look. Thanks!

**Comment by paulcsyapse** [comment]
I'll take care of it later today. I am usually pretty careful to keep my
work account out of other stuff, but I understand the point in this case.

**Comment by paulcsyapse** [comment]
Added to contact info. See https://www.linkedin.com/in/paul-callahan-0290b11/

**Comment by paulcsyapse** [comment]
Ping? I added the link a few days back and put a comment on github.

**Comment by zestyping** [comment]
Hi @paulcsyapse, sorry for the delay.  I see the link now and have added your signature to the site.  Thank you!

**Pull request merged**
