### PR TITLE
Merge pull request #1 from neveragaindottech/master

### PR DESCRIPTION
**Pull request by znmeb**
Add myself to the list

### CODE REVIEW

**Comment by hurtstotouchfire** [comment]
Hey there, I don't see a commit adding your name here. Have you pushed your master branch?

**Comment by znmeb** [comment]
I thought I did ... let me go check it.

**Comment by hurtstotouchfire** [comment]
Let me know if you need any guidance on updating your branches.

**Comment by lizthegrey** [comment]
Please use https://sign.neveragain.tech/ if you're having technical difficulties with github.

**Pull request closed without merging**
