### PR TITLE
Create Daryl_Anderman_Freelancer.md

### PR DESCRIPTION
**Pull request by danderman**

### CODE REVIEW

**Comment by zestyping** [comment]
Hi, we don't have enough information to verify that this GitHub account is owned by Daryl Anderman.  Can you help us confirm this?  A link to a LinkedIn profile, or a message approving this PR in a tweet or website owned by Daryl Anderman would work.  Thanks!

**Comment by danderman** [comment]
Whoops!  I guess I don't use github that much.  Here are my LinkedIn and Upwork profiles:
https://www.linkedin.com/in/daryl-anderman-60643260 <https://www.linkedin.com/in/daryl-anderman-60643260>
http://www.upwork.com/o/profiles/users/_~01124c8529f0e6ef0e/ <http://www.upwork.com/o/profiles/users/_~01124c8529f0e6ef0e/>

Thanks!
Daryl

**Comment by ichthyos** [comment]
Hi Daryl, sorry for the back and forth on this. Thank you for your pull request and response.  To add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Could you please put a link to your GitHub account on an established webpage (such as your Keybase or LinkedIn profile, or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.

Thanks!

**Comment by danderman** [comment]
No trouble, thanks for keeping on it.

I've added my github link to my LinkedIn under Contact Info or Websites:
https://ca.linkedin.com/in/daryl-anderman-60643260

Daryl

**Comment by ichthyos** [comment]
Great -- identity verified. I just took a look at the contents of the commit. Unfortunately, it's not in the right format, so we can't accept it as is.
Please follow the instructions and the template exactly at https://github.com/neveragaindottech/neveragaindottech.github.io/blob/master/README.md -- feel free to update this pull request or make a new one. I'll merge it in when it's in the right format.

Thanks again!

**Pull request merged**
