### PR TITLE
Create Paul_Bjorkstrand.md

### PR DESCRIPTION
**Pull request by paul-bjorkstrand**

### CODE REVIEW

**Comment by dhartunian** [comment]
@paul-bjorkstrand can you verify your identity in any way? link it to a linkedin or something?

**Comment by paul-bjorkstrand** [comment]
https://www.linkedin.com/in/paul-bjorkstrand-4b331947,

**Comment by RichardEpsilonHughes** [comment]
@paul-bjorkstrand Can you add your github to that linkedin so we can be certain it's yours?

**Comment by paul-bjorkstrand** [comment]
LinkedIn with Github link there. Apologies for the delay.

**Comment by RichardEpsilonHughes** [comment]
Welcome to the host, Paul.

**Pull request merged**
