### PR TITLE
added Taurean Bryant

### PR DESCRIPTION
**Pull request by taurean**
Added github user @taurean, @_taurean on twitter.

### CODE REVIEW

**Comment by bigethan** [comment]
coming in via mega commit to avoid comments

**Comment by taurean** [comment]
@bigethan Hey sorry, can you expand on what you meant? I'll make the fix right after. (First time creating a pull request in someone else's repo)

**Comment by bigethan** [comment]
sure, you're on the list now :-) we were getting too many merge conflicts so we just took everyone's names and submitted on big patch.  It's up:  http://neveragain.tech/

Sorry for the lack of clarity, a little sleepy / in roboto mode :-)

**Comment by taurean** [comment]
No worries, thanks for taking the time to clarify :)

**Pull request closed without merging**
