### PR TITLE
Create William_Fishburne_AcqSIS.md

### PR DESCRIPTION
**Pull request by bfishburne**

### CODE REVIEW

**Comment by zestyping** [comment]
I'm sorry, I don't have enough information to confirm that William Fishburne of AcqSIS is submitting this pull request.  We need to verify that William Fishburne of AcqSIS owns the GitHub user account bfishburne.  Can you provide a link to a profile on LinkedIn or a website that establishes that connection?  Thank you.

**Comment by bfishburne** [comment]
I do not have linked in, but my acqsis account forwards here.
Brett.fishburne@acqsis.com

You can also ask my partner, Calvin Stone whose email is at the acqSIS.com
website!

William "Brett" Fishburne

**Comment by lizthegrey** [comment]
Sent an email to your acqsis account.

**Comment by lizthegrey** [comment]
Private confirmation received.

**Pull request merged**
