### PR TITLE
Add Neil Spence.

### PR DESCRIPTION
**Pull request by sfneil**

### CODE REVIEW

**Comment by emhoracek** [comment]
Hi, can you rebase, if possible?

**Comment by sfneil** [comment]
I'm sorry, I'm a very old school dev and joined github specifically to add my name to this. This being my first time here, I'm not exactly sure how to proceed.

**Comment by emhoracek** [comment]
@sfneil No problem! It just might take a little longer to get your signature added.

**Comment by sfneil** [comment]
Did I make a mess?

**Comment by zestyping** [comment]
I've fixed the merge conflict and added you.  Thanks for signing!

**Pull request closed without merging**
