### PR TITLE
Revert "Add Kent Brewster to signature list"

### PR DESCRIPTION
**Pull request by emhoracek**
Reverts neveragaindottech/neveragaindottech.github.io#141

### CODE REVIEW

**Comment by emhoracek** [comment]
Sorry I got excited and didn't do proper review. >_<

**Comment by emhoracek** [comment]
This pull request removed two signatures as well as adding one.

**Comment by emhoracek** [comment]
I will add @kentbrew directly to master.

**Comment by kentbrew** [comment]
Thanks for taking good care of us!

**Pull request merged**
