### PR TITLE
Create Raven_Alder.md

### PR DESCRIPTION
**Pull request by banfennid**

### CODE REVIEW

**Comment by jacquesf** [comment]
Hi, thank you for your pull request.  To add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Could you please put a link to your GitHub account on an established webpage (such as your LinkedIn profile or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.

Thanks!

**Comment by banfennid** [comment]
Hiya --

* Jacques Fortier <notifications@github.com> [2016-12-15 23:29:00
* -0800]:
> Hi, thank you for your pull request.  To add this signature to the
> pledge, we need to verify that this signature accurately represents
> the owner of this GitHub account.
> 
> Could you please put a link to your GitHub account on an established
> webpage (such as your LinkedIn profile or personal site) that
> represents you by the name and affiliation in your signature? Please
> reply with the URL of that webpage, and we'll take a look.

	I don't have a personal site, or LinkedIn, or Facebook,
unfortunately.  (Being intentionally low-profile has its costs!)  I
could send you a photo of my business card, if that would help, or I
could reply to you from my work email which has the name and affiliation
in my signature in its signature.  (ralder@nexuminc.com is me at work.)
Let me know if either of those would be sufficient.

Cheers,
Raven 

-- 
@

**Comment by ichthyos** [comment]
Hi Raven, yes the work email verification will work for me. Just sent you a message to reply to.

**Comment by ichthyos** [comment]
Received requested verification.

**Pull request merged**
