### PR TITLE
Create Karl_A_Krueger.md

### PR DESCRIPTION
**Pull request by thatkarlperson**
I'm not very active on Github or a lot of other places.
Email if you need further confirmation.
Thank you for doing this.

### CODE REVIEW

**Comment by zestyping** [comment]
Hi Karl, I don't see a usable email address on your GitHub profile so I can't email you.  Can you provide anything that connects your full name to your GitHub account, like a personal website or blog or LinkedIn page or Keybase page or anything like that?  Thanks!

**Comment by thatkarlperson** [comment]
Hey there, it's been a while! Looks like Github emailed me for your request.

So ... does this message itself count?

On Dec 19, 2016 9:42 PM, "Ka-Ping Yee" <notifications@github.com> wrote:

Hi Karl, I don't see a usable email address on your GitHub profile so I
can't email you. Can you provide anything that connects your full name to
your GitHub account, like a personal website or blog or LinkedIn page or
Keybase page or anything like that? Thanks!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/neveragaindottech/neveragaindottech.github.io/pull/2069#issuecomment-268160339>,
or mute the thread

**Comment by lizthegrey** [comment]
I can confirm Karl out of band.

**Comment by lizthegrey** [comment]
Confirmed.

**Pull request merged**
