### PR TITLE
Create Mirand_.md

### PR DESCRIPTION
**Pull request by thebestday27**

### CODE REVIEW

**Comment by natdempk** [comment]
Hi @thebestday27 can you format your `.md` file to match the format given in the template here? https://github.com/neveragaindottech/neveragaindottech.github.io/blob/master/template.md

**Comment by thebestday27** [comment]
Hello Nathaniel, I sent you my formatted file .md a few minutes ago as demanded, I hope that works and it can be mentioned, Merry Christmas to you, your team and your families. Yours sincerely, @thebestday27.
 

    On Friday, December 16, 2016 8:57 AM, Nathaniel Dempkowski <notifications@github.com> wrote:
 

 Hi @thebestday27 can you format your .md file to match the format given in the template here? https://github.com/neveragaindottech/neveragaindottech.github.io/blob/master/template.md—

**Comment by natdempk** [comment]
Hi @thebestday27 

Right now the file you initially submitted doesn't match the format of the template we need to be able to merge it. Can you update it so that it matches the format here: https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.md

If you update it to match the format in another commit, we will be able to merge it. 

Additionally, to add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.

Could you please put a link to your GitHub account on an established webpage (such as your LinkedIn profile or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.

Thanks!

**Comment by thebestday27** [comment]
Dear Nathaniel,Good morning, I hope you are very well. I send you my updated and formattedfile, I hope it works this time and my name can be added on the listof signatures to the commitment. In addition I also send you a linkwith my research work as recommended in your last message, you cancheck it if you have a lot of mistrust. You should note too that Ihave created my GitHub account only to sign your pledge which Iconsider necessary, for that reason I prefer if my link is notpublished, only my name and affiliation. -Seemy Post-Scriptum herebelow-. I thank you in advance for yourresponse,Have a very good day, Yours sincerely, Miranda.@thebestday27 : GitHub name
Post-Scriptum:My link is directly associatedto the Open Government Partnership under the authority of thePrime-Minister Office -Secretariat of Government-, selected andapproved by a team of specialists in that subject (the StateLaboratory - EtaLab) so it is not for business or commercialisation.Thank you.
https://fr.ogpsummit.org/events/01-project-everything-counts-in-larger-amounts-space-art-and-architecture-about-algorithms-and-robots-as-factors-in-contemporary-mutations/
 

    On Friday, December 16, 2016 6:46 PM, Nathaniel Dempkowski <notifications@github.com> wrote:
 

 Hi @thebestday27Right now the file you initially submitted doesn't match the format of the template we need to be able to merge it. Can you update it so that it matches the format here: https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.mdIf you update it to match the format in another commit, we will be able to merge it.Additionally, to add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.Could you please put a link to your GitHub account on an established webpage (such as your LinkedIn profile or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.Thanks!—

**Comment by thebestday27** [comment]
DearNathaniel,
Goodmorning,I hopeyou're very well, I sendyou this message because I want you close my GitHub account since hasbeen created with the only purpose to confirm my solidarity andcommitment to the Never Again Tech pledge wich I consider a moralimperative as real, and in view that you do not have the intention topublish my signature with my commitment I do not find the need tocontinue having an GitHub account or similar. I thank you for yourgood willingness. On theother hand, on the contrary, I share with you this message of Christmas to you, yourfamilies and your friends, Please receive here below an e-card forChristmas time,Also Ishare with you an e- tribute to a magnificent city and its citizens:Berlin. All Parisians, France and the world are with Berlin now afterthe tragedy happened yesterday evening. All solidarity to Berlin andGermany: We are Berlin - ICH BIN EIN BERLINER, pray for Berlin. Weare alive and we will live.A MerryChristmas to you, your families, your friends and your team.I sendyou my best wishes to the next year a Happy New Year 2017 for yourhappiness and your best projects.Yourssincerely,Miranda.



    On Friday, December 16, 2016 6:46 PM, Nathaniel Dempkowski <notifications@github.com> wrote:
 

 Hi @thebestday27Right now the file you initially submitted doesn't match the format of the template we need to be able to merge it. Can you update it so that it matches the format here: https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.mdIf you update it to match the format in another commit, we will be able to merge it.Additionally, to add this signature to the pledge, we need to verify that this signature accurately represents the owner of this GitHub account.Could you please put a link to your GitHub account on an established webpage (such as your LinkedIn profile or personal site) that represents you by the name and affiliation in your signature? Please reply with the URL of that webpage, and we'll take a look.Thanks!—

**Pull request closed without merging**
