### PR TITLE
Add employees from Automattic

### PR DESCRIPTION
**Pull request by melchoyce**
Thanks for doing this! My company rallied together to do a group PR. 

I am submitting this PR on behalf of:

Anne McCarthy
Ashleigh Axios
Aviva Pinchas
Caroline Moore
Cheri Lucas Rowlands
Chris Rudzki
Corey McKrill
Daryl L. L. Houston
Diana Potter
Doug Aitken
Elizabeth Urello
Enej Bajgorić
James Huff
James Tien
John Maeda
Justin Shreve
Kellie Peterson
Laurel Fulford
Liz Karkosk
Lori McLeese
Marjorie R. Asturias
Mark Armstrong
Mark Drovdahl
Matt Perry
Matt Sherman
Mel Choyce
Melanie Harari
Mindy Postoff
Nick Daugherty
Payton Swick
Philip John
Rodrigo Primo
Ryan Boren
Ryan Cowles
Ryan Markel
Steve Blythe
Stéphane Boisvert
Toni Schneider

### CODE REVIEW

**Comment by zestyping** [comment]
Hi, Mel!  Wow, it's so awesome that the entire company wants to sign!

We are doing our best to handle and verify lots of incoming signature requests, so we've been trying to keep our policy simple and are not accepting requests on behalf of other people without further verification.

There are probably many ways we could do this, but maybe the quickest way to verify all these signatures is to see that there's a page somewhere on https://automattic.com/ listing everyone's name and asserting they are employees of Automattic who consent to sign, with a link to this PR.  Would that be feasible for you?

**Comment by vaurora** [comment]
Mel, thank you so much for this work and the great idea! We want to do a little extra confirmation since this is so many people at once, so I emailed one of the signatories asking for confirmation. Could you get at least one other signatory to email neveragaindottech@gmail.com from their Automattic.com email address to say they agree to sign? And could you email neveragaindottech@gmail.com as well so we can figure out how to make it easier for future group signatures to happen?

Again, this is a great idea, thank you so much for doing it!

**Comment by melchoyce** [comment]
Thank you @vaurora, will do :)

**Comment by RichardEpsilonHughes** [comment]
To all of you in the Automattic team: thank you.

**Comment by vaurora** [comment]
Update: @melchoyce wants to do one more check before this PR is merged. Please wait for her okay on this PR before merging it. @melchoyce, please email us again when it is ready to go!

**Comment by brahn** [comment]
@vaurora @melchoyce @zestyping was looking into doing something similar. No problem having a bunch of folks email neveragaindottech@gmail.com but please let me know if there's a preferred way of doing business.  Thanks!

**Comment by brahn** [comment]
(ended up submitting https://github.com/neveragaindottech/neveragaindottech.github.io/pull/1703 )

**Pull request merged**
