### PR TITLE
Create peter_kropf.md

### PR DESCRIPTION
**Pull request by pkropf**
My LinkedIn profile can be found at https://www.linkedin.com/in/pkropf/. Personal web site http://peterkropf.com. Github profile https://github.com/pkropf.

### CODE REVIEW

**Comment by RichardEpsilonHughes** [comment]
Welcome, Peter. May you find success continuing to spread the meme.

**Comment by pkropf** [comment]
Can we pull the affiliation? I misunderstood its purpose.

**Comment by RichardEpsilonHughes** [comment]
Yes, one moment.

**Comment by RichardEpsilonHughes** [comment]
Edited.

**Comment by pkropf** [comment]
Thanks

**Pull request merged**
