### PR TITLE
Create Roger_Kriekenbeck_Application_Developer_Quest_Software.md

### PR DESCRIPTION
**Pull request by rrkriek**

### CODE REVIEW

**Comment by dhartunian** [comment]
@rrkriek is there any way you can verify your identity on github? You account is very recently created so just want to make sure it's you.

**Comment by rrkriek** [comment]
Hi David –

I thought I had verified my identity already.  Let me know what you need me to do.

Thanks!
Roger Kriekenbeck (aka rrkriek)

Dell | Application Mgmt. Sr. Advisor | Dell Software Group IT
Office +1 949 754 8135 | Mobile +1 425 227 5124
roger.kriekenbeck@software.dell.com<mailto:roger.kriekenbeck@software.dell.com>

**Comment by rrkriek** [comment]
Hello, this is rrkriek.  i am responding to the request to verify my id.

thanks!
roger kriekenbeck

**Comment by ichthyos** [comment]
Hi Roger,

Apologies for the back and forth on this -- we're facing a high volume of incoming requests and are doing our best to keep up. Could you do two things?

1. Add quotation marks around the fields in your sig file to make it look like https://raw.githubusercontent.com/neveragaindottech/neveragaindottech.github.io/master/template.md.

2. Add your name to your GitHub profile: https://github.com/settings/profile.

Thanks!

**Pull request merged**
